# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family='Maple Mono NF' style=Bold features=+calt
bold_font        family='Maple Mono NF' style=ExtraBold features=+calt
italic_font      family='Maple Mono NF' style='ExtraBold Italic' features=+calt
bold_italic_font auto
font_size 11.5
# END_KITTY_FONTS

#---custom---
window_padding_width 7
hide_window_decorations no
background_opacity 0.3
cursor_shape beam
cursor_beam_thickness 2
cursor_trail 1
cursor_trail_decay 0.1 0.4
